### ISSUE TITLE
#966 Migrate: Import from Types

### ISSUE THREAD

**Issue by jaecSolutions** [jaecSolutions/John-Beta-Autosync-with-EmptyGithub#142]
From this ticket I'm trying to look into Types and how we can create an importer for Pods

## To-dos

- [ ] Lay out where data is stored for content type settings (Post Types / Taxonomies)
- [ ] Consider how best to map content type settings over to Pods (if there are matches for each, or where they differ)
- [ ] Lay out where data is stored for custom field settings
- [ ] Consider how best to map Types field types/settings over to Pods (if there are matches for each, or where they differ)
- [ ] Confirm whether or not Types stores ALL field data in wp_postmeta and if it's stored cleanly
